version: '3'
services:
  app:
      container_name: IEProjekt
      restart: always
      build: .
      ports:
        - '80:3000'
      links:
        - mongo
  mongo:
      container_name: mongo
      image: mongo
      ports:
        - '37001:37001'